FL_hip_joint:
  limit:
    lower: -1.01
    upper: 1.01
    velocity: 22.0
    effort: 120.0

FL_thigh_joint:
  limit:
    lower: -2.34
    upper: 3.15
    velocity: 22.0
    effort: 120.0

FL_calf_joint:
  limit:
    lower: -2.77
    upper: -0.54
    velocity: 14.6667
    effort: 180.0

FR_hip_joint:
  limit:
    lower: -1.01
    upper: 1.01
    velocity: 22.0
    effort: 120.0

FR_thigh_joint:
  limit:
    lower: -2.34
    upper: 3.15
    velocity: 22.0
    effort: 120.0

FR_calf_joint:
  limit:
    lower: -2.77
    upper: -0.54
    velocity: 14.6667
    effort: 180.0

RL_hip_joint:
  limit:
    lower: -1.01
    upper: 1.01
    velocity: 22.0
    effort: 120.0

RL_thigh_joint:
  limit:
    lower: -1.56
    upper: 3.94
    velocity: 22.0
    effort: 120.0

RL_calf_joint:
  limit:
    lower: -2.77
    upper: -0.54
    velocity: 14.6667
    effort: 180.0

RR_hip_joint:
  limit:
    lower: -1.01
    upper: 1.01
    velocity: 22.0
    effort: 120.0

RR_thigh_joint:
  limit:
    lower: -1.56
    upper: 3.94
    velocity: 22.0
    effort: 120.0

RR_calf_joint:
  limit:
    lower: -2.77
    upper: -0.54
    velocity: 14.6667
    effort: 180.0
